name: build

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - '*.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '*.md'

jobs:
  shfmt:
    name: runner / shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-shfmt@v1
        with:
          shfmt_flags: -i 2 -sr -ci -d

  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}

  test-on-cross-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-13
          - macOS-latest
        version:
          - 0.16.2
          - 0.16.3
          - 0.16.4
          - latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          nimble-version: ${{ matrix.version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Nimble version
        run: nimble -v

  test-multi-versions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        version:
          - 0.16.2
          - 0.16.3          
          - latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          nimble-version: ${{ matrix.version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Nimble version
        run: nimble -v

  test-parent-directory:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          nimble-version: 0.16.3
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          parent-nimble-install-directory: ${{ runner.temp }}

      - name: Print Nimble version
        run: nimble -v
